# Generated by Django 4.1.1 on 2022-10-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeismicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('depth', models.SmallIntegerField(null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
