# Generated by Django 4.1.1 on 2022-10-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvdata', '0003_alter_seismicevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='seismicevent',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
